#!/usr/bin/python
import os
import sys

sys.path.insert(0, os.path.dirname(__file__) or '.')
sys.path.insert(0, '..')

PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python")

virtenv = PY_DIR + '/virtenv/'

PY_CACHE = os.path.join(virtenv, 'lib', os.environ['OPENSHIFT_PYTHON_VERSION'], 'site-packages')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    exec(open(virtualenv).read(), dict(__file__=virtualenv))
except IOError:
    pass

from ahye import app as application
from ahye.settings import DEBUG
from ahye.flaskext.mako import init_mako

application.config.update({
    'MAKO_DIR': os.path.join(os.environ['OPENSHIFT_HOMEDIR'], 'app-root', 'repo', 'ahye', 'templates'),
    'MAKO_CACHEDIR': '/tmp',
    'MAKO_CACHESIZE': 500,
    'DEBUG': True
})
init_mako(application)
